// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: velkarwalletd.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_velkarwalletd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_velkarwalletd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_velkarwalletd_proto_rawDescGZIP(), []int{0}
}

type GetBalanceResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Available       uint64                 `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Pending         uint64                 `protobuf:"varint,2,opt,name=pending,proto3" json:"pending,omitempty"`
	AddressBalances []*AddressBalances     `protobuf:"bytes,3,rep,name=addressBalances,proto3" json:"addressBalances,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_velkarwalletd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_velkarwalletd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_velkarwalletd_proto_rawDescGZIP(), []int{1}
}

func (x *GetBalanceResponse) GetAvailable() uint64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *GetBalanceResponse) GetPending() uint64 {
	if x != nil {
		return x.Pending
	}
	return 0
}

func (x *GetBalanceResponse) GetAddressBalances() []*AddressBalances {
	if x != nil {
		return x.AddressBalances
	}
	return nil
}

type AddressBalances struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Available     uint64                 `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	Pending       uint64                 `protobuf:"varint,3,opt,name=pending,proto3" json:"pending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressBalances) Reset() {
	*x = AddressBalances{}
	mi := &file_velkarwalletd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressBalances) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressBalances) ProtoMessage() {}

func (x *AddressBalances) ProtoReflect() protoreflect.Message {
	mi := &file_velkarwalletd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressBalances.ProtoReflect.Descriptor instead.
func (*AddressBalances) Descriptor() ([]byte, []int) {
	return file_velkarwalletd_proto_rawDescGZIP(), []int{2}
}

func (x *AddressBalances) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddressBalances) GetAvailable() uint64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *AddressBalances) GetPending() uint64 {
	if x != nil {
		return x.Pending
	}
	return 0
}

type FeePolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to FeePolicy:
	//
	//	*FeePolicy_MaxFeeRate
	//	*FeePolicy_ExactFeeRate
	//	*FeePolicy_MaxFee
	FeePolicy     isFeePolicy_FeePolicy `protobuf_oneof:"feePolicy"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeePolicy) Reset() {
	*x = FeePolicy{}
	mi := &file_velkarwalletd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeePolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeePolicy) ProtoMessage() {}

func (x *FeePolicy) ProtoReflect() protoreflect.Message {
	mi := &file_velkarwalletd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeePolicy.ProtoReflect.Descriptor instead.
func (*FeePolicy) Descriptor() ([]byte, []int) {
	return file_velkarwalletd_proto_rawDescGZIP(), []int{3}
}

func (x *FeePolicy) GetFeePolicy() isFeePolicy_FeePolicy {
	if x != nil {
		return x.FeePolicy
	}
	return nil
}

func (x *FeePolicy) GetMaxFeeRate() float64 {
	if x != nil {
		if x, ok := x.FeePolicy.(*FeePolicy_MaxFeeRate); ok {
			return x.MaxFeeRate
		}
	}
	return 0
}

func (x *FeePolicy) GetExactFeeRate() float64 {
	if x != nil {
		if x, ok := x.FeePolicy.(*FeePolicy_ExactFeeRate); ok {
			return x.ExactFeeRate
		}
	}
	return 0
}

func (x *FeePolicy) GetMaxFee() uint64 {
	if x != nil {
		if x, ok := x.FeePolicy.(*FeePolicy_MaxFee); ok {
			return x.MaxFee
		}
	}
	return 0
}

type isFeePolicy_FeePolicy interface {
	isFeePolicy_FeePolicy()
}

type FeePolicy_MaxFeeRate struct {
	MaxFeeRate float64 `protobuf:"fixed64,6,opt,name=maxFeeRate,proto3,oneof"`
}

type FeePolicy_ExactFeeRate struct {
	ExactFeeRate float64 `protobuf:"fixed64,7,opt,name=exactFeeRate,proto3,oneof"`
}

type FeePolicy_MaxFee struct {
	MaxFee uint64 `protobuf:"varint,8,opt,name=maxFee,proto3,oneof"`
}

func (*FeePolicy_MaxFeeRate) isFeePolicy_FeePolicy() {}

func (*FeePolicy_ExactFeeRate) isFeePolicy_FeePolicy() {}

func (*FeePolicy_MaxFee) isFeePolicy_FeePolicy() {}

type CreateUnsignedTransactionsRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Address                  string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Amount                   uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	From                     []string               `protobuf:"bytes,3,rep,name=from,proto3" json:"from,omitempty"`
	UseExistingChangeAddress bool                   `protobuf:"varint,4,opt,name=useExistingChangeAddress,proto3" json:"useExistingChangeAddress,omitempty"`
	IsSendAll                bool                   `protobuf:"varint,5,opt,name=isSendAll,proto3" json:"isSendAll,omitempty"`
	FeePolicy                *FeePolicy             `protobuf:"bytes,6,opt,name=feePolicy,proto3" json:"feePolicy,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CreateUnsignedTransactionsRequest) Reset() {
	*x = CreateUnsignedTransactionsRequest{}
	mi := &file_velkarwalletd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUnsignedTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUnsignedTransactionsRequest) ProtoMessage() {}

func (x *CreateUnsignedTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_velkarwalletd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUnsignedTransactionsRequest.ProtoReflect.Descriptor instead.
func (*CreateUnsignedTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_velkarwalletd_proto_rawDescGZIP(), []int{4}
}

func (x *CreateUnsignedTransactionsRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateUnsignedTransactionsRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateUnsignedTransactionsRequest) GetFrom() []string {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *CreateUnsignedTransactionsRequest) GetUseExistingChangeAddress() bool {
	if x != nil {
		return x.UseExistingChangeAddress
	}
	return false
}

func (x *CreateUnsignedTransactionsRequest) GetIsSendAll() bool {
	if x != nil {
		return x.IsSendAll
	}
	return false
}

func (x *CreateUnsignedTransactionsRequest) GetFeePolicy() *FeePolicy {
	if x != nil {
		return x.FeePolicy
	}
	return nil
}

type CreateUnsignedTransactionsResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UnsignedTransactions [][]byte               `protobuf:"bytes,1,rep,name=unsignedTransactions,proto3" json:"unsignedTransactions,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateUnsignedTransactionsResponse) Reset() {
	*x = CreateUnsignedTransactionsResponse{}
	mi := &file_velkarwalletd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUnsignedTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUnsignedTransactionsResponse) ProtoMessage() {}

func (x *CreateUnsignedTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_velkarwalletd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUnsignedTransactionsResponse.ProtoReflect.Descriptor instead.
func (*CreateUnsignedTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_velkarwalletd_proto_rawDescGZIP(), []int{5}
}

func (x *CreateUnsignedTransactionsResponse) GetUnsignedTransactions() [][]byte {
	if x != nil {
		return x.UnsignedTransactions
	}
	return nil
}

type ShowAddressesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowAddressesRequest) Reset() {
	*x = ShowAddressesRequest{}
	mi := &file_velkarwalletd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowAddressesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowAddressesRequest) ProtoMessage() {}

func (x *ShowAddressesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_velkarwalletd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowAddressesRequest.ProtoReflect.Descriptor instead.
func (*ShowAddressesRequest) Descriptor() ([]byte, []int) {
	return file_velkarwalletd_proto_rawDescGZIP(), []int{6}
}

type ShowAddressesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []string               `protobuf:"bytes,1,rep,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowAddressesResponse) Reset() {
	*x = ShowAddressesResponse{}
	mi := &file_velkarwalletd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowAddressesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowAddressesResponse) ProtoMessage() {}

func (x *ShowAddressesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_velkarwalletd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowAddressesResponse.ProtoReflect.Descriptor instead.
func (*ShowAddressesResponse) Descriptor() ([]byte, []int) {
	return file_velkarwalletd_proto_rawDescGZIP(), []int{7}
}

func (x *ShowAddressesResponse) GetAddress() []string {
	if x != nil {
		return x.Address
	}
	return nil
}

type NewAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewAddressRequest) Reset() {
	*x = NewAddressRequest{}
	mi := &file_velkarwalletd_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewAddressRequest) ProtoMessage() {}

func (x *NewAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_velkarwalletd_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewAddressRequest.ProtoReflect.Descriptor instead.
func (*NewAddressRequest) Descriptor() ([]byte, []int) {
	return file_velkarwalletd_proto_rawDescGZIP(), []int{8}
}

type NewAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewAddressResponse) Reset() {
	*x = NewAddressResponse{}
	mi := &file_velkarwalletd_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewAddressResponse) ProtoMessage() {}

func (x *NewAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_velkarwalletd_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewAddressResponse.ProtoReflect.Descriptor instead.
func (*NewAddressResponse) Descriptor() ([]byte, []int) {
	return file_velkarwalletd_proto_rawDescGZIP(), []int{9}
}

func (x *NewAddressResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type BroadcastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDomain      bool                   `protobuf:"varint,1,opt,name=isDomain,proto3" json:"isDomain,omitempty"`
	Transactions  [][]byte               `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastRequest) Reset() {
	*x = BroadcastRequest{}
	mi := &file_velkarwalletd_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastRequest) ProtoMessage() {}

func (x *BroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_velkarwalletd_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastRequest.ProtoReflect.Descriptor instead.
func (*BroadcastRequest) Descriptor() ([]byte, []int) {
	return file_velkarwalletd_proto_rawDescGZIP(), []int{10}
}

func (x *BroadcastRequest) GetIsDomain() bool {
	if x != nil {
		return x.IsDomain
	}
	return false
}

func (x *BroadcastRequest) GetTransactions() [][]byte {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type BroadcastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxIDs         []string               `protobuf:"bytes,1,rep,name=txIDs,proto3" json:"txIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastResponse) Reset() {
	*x = BroadcastResponse{}
	mi := &file_velkarwalletd_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastResponse) ProtoMessage() {}

func (x *BroadcastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_velkarwalletd_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastResponse.ProtoReflect.Descriptor instead.
func (*BroadcastResponse) Descriptor() ([]byte, []int) {
	return file_velkarwalletd_proto_rawDescGZIP(), []int{11}
}

func (x *BroadcastResponse) GetTxIDs() []string {
	if x != nil {
		return x.TxIDs
	}
	return nil
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_velkarwalletd_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_velkarwalletd_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_velkarwalletd_proto_rawDescGZIP(), []int{12}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_velkarwalletd_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_velkarwalletd_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_velkarwalletd_proto_rawDescGZIP(), []int{13}
}

type Outpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	Index         uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Outpoint) Reset() {
	*x = Outpoint{}
	mi := &file_velkarwalletd_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outpoint) ProtoMessage() {}

func (x *Outpoint) ProtoReflect() protoreflect.Message {
	mi := &file_velkarwalletd_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outpoint.ProtoReflect.Descriptor instead.
func (*Outpoint) Descriptor() ([]byte, []int) {
	return file_velkarwalletd_proto_rawDescGZIP(), []int{14}
}

func (x *Outpoint) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Outpoint) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type UtxosByAddressesEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Outpoint      *Outpoint              `protobuf:"bytes,2,opt,name=outpoint,proto3" json:"outpoint,omitempty"`
	UtxoEntry     *UtxoEntry             `protobuf:"bytes,3,opt,name=utxoEntry,proto3" json:"utxoEntry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UtxosByAddressesEntry) Reset() {
	*x = UtxosByAddressesEntry{}
	mi := &file_velkarwalletd_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UtxosByAddressesEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UtxosByAddressesEntry) ProtoMessage() {}

func (x *UtxosByAddressesEntry) ProtoReflect() protoreflect.Message {
	mi := &file_velkarwalletd_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UtxosByAddressesEntry.ProtoReflect.Descriptor instead.
func (*UtxosByAddressesEntry) Descriptor() ([]byte, []int) {
	return file_velkarwalletd_proto_rawDescGZIP(), []int{15}
}

func (x *UtxosByAddressesEntry) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UtxosByAddressesEntry) GetOutpoint() *Outpoint {
	if x != nil {
		return x.Outpoint
	}
	return nil
}

func (x *UtxosByAddressesEntry) GetUtxoEntry() *UtxoEntry {
	if x != nil {
		return x.UtxoEntry
	}
	return nil
}

type ScriptPublicKey struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Version         uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ScriptPublicKey string                 `protobuf:"bytes,2,opt,name=scriptPublicKey,proto3" json:"scriptPublicKey,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ScriptPublicKey) Reset() {
	*x = ScriptPublicKey{}
	mi := &file_velkarwalletd_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptPublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptPublicKey) ProtoMessage() {}

func (x *ScriptPublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_velkarwalletd_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptPublicKey.ProtoReflect.Descriptor instead.
func (*ScriptPublicKey) Descriptor() ([]byte, []int) {
	return file_velkarwalletd_proto_rawDescGZIP(), []int{16}
}

func (x *ScriptPublicKey) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ScriptPublicKey) GetScriptPublicKey() string {
	if x != nil {
		return x.ScriptPublicKey
	}
	return ""
}

type UtxoEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Amount          uint64                 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	ScriptPublicKey *ScriptPublicKey       `protobuf:"bytes,2,opt,name=scriptPublicKey,proto3" json:"scriptPublicKey,omitempty"`
	BlockDaaScore   uint64                 `protobuf:"varint,3,opt,name=blockDaaScore,proto3" json:"blockDaaScore,omitempty"`
	IsCoinbase      bool                   `protobuf:"varint,4,opt,name=isCoinbase,proto3" json:"isCoinbase,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UtxoEntry) Reset() {
	*x = UtxoEntry{}
	mi := &file_velkarwalletd_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UtxoEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UtxoEntry) ProtoMessage() {}

func (x *UtxoEntry) ProtoReflect() protoreflect.Message {
	mi := &file_velkarwalletd_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UtxoEntry.ProtoReflect.Descriptor instead.
func (*UtxoEntry) Descriptor() ([]byte, []int) {
	return file_velkarwalletd_proto_rawDescGZIP(), []int{17}
}

func (x *UtxoEntry) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UtxoEntry) GetScriptPublicKey() *ScriptPublicKey {
	if x != nil {
		return x.ScriptPublicKey
	}
	return nil
}

func (x *UtxoEntry) GetBlockDaaScore() uint64 {
	if x != nil {
		return x.BlockDaaScore
	}
	return 0
}

func (x *UtxoEntry) GetIsCoinbase() bool {
	if x != nil {
		return x.IsCoinbase
	}
	return false
}

type GetExternalSpendableUTXOsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExternalSpendableUTXOsRequest) Reset() {
	*x = GetExternalSpendableUTXOsRequest{}
	mi := &file_velkarwalletd_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExternalSpendableUTXOsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExternalSpendableUTXOsRequest) ProtoMessage() {}

func (x *GetExternalSpendableUTXOsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_velkarwalletd_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExternalSpendableUTXOsRequest.ProtoReflect.Descriptor instead.
func (*GetExternalSpendableUTXOsRequest) Descriptor() ([]byte, []int) {
	return file_velkarwalletd_proto_rawDescGZIP(), []int{18}
}

func (x *GetExternalSpendableUTXOsRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetExternalSpendableUTXOsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Entries       []*UtxosByAddressesEntry `protobuf:"bytes,1,rep,name=Entries,proto3" json:"Entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExternalSpendableUTXOsResponse) Reset() {
	*x = GetExternalSpendableUTXOsResponse{}
	mi := &file_velkarwalletd_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExternalSpendableUTXOsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExternalSpendableUTXOsResponse) ProtoMessage() {}

func (x *GetExternalSpendableUTXOsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_velkarwalletd_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExternalSpendableUTXOsResponse.ProtoReflect.Descriptor instead.
func (*GetExternalSpendableUTXOsResponse) Descriptor() ([]byte, []int) {
	return file_velkarwalletd_proto_rawDescGZIP(), []int{19}
}

func (x *GetExternalSpendableUTXOsResponse) GetEntries() []*UtxosByAddressesEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type SendRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ToAddress                string                 `protobuf:"bytes,1,opt,name=toAddress,proto3" json:"toAddress,omitempty"`
	Amount                   uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Password                 string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	From                     []string               `protobuf:"bytes,4,rep,name=from,proto3" json:"from,omitempty"`
	UseExistingChangeAddress bool                   `protobuf:"varint,5,opt,name=useExistingChangeAddress,proto3" json:"useExistingChangeAddress,omitempty"`
	IsSendAll                bool                   `protobuf:"varint,6,opt,name=isSendAll,proto3" json:"isSendAll,omitempty"`
	FeePolicy                *FeePolicy             `protobuf:"bytes,7,opt,name=feePolicy,proto3" json:"feePolicy,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_velkarwalletd_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_velkarwalletd_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_velkarwalletd_proto_rawDescGZIP(), []int{20}
}

func (x *SendRequest) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *SendRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SendRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SendRequest) GetFrom() []string {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *SendRequest) GetUseExistingChangeAddress() bool {
	if x != nil {
		return x.UseExistingChangeAddress
	}
	return false
}

func (x *SendRequest) GetIsSendAll() bool {
	if x != nil {
		return x.IsSendAll
	}
	return false
}

func (x *SendRequest) GetFeePolicy() *FeePolicy {
	if x != nil {
		return x.FeePolicy
	}
	return nil
}

type SendResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TxIDs              []string               `protobuf:"bytes,1,rep,name=txIDs,proto3" json:"txIDs,omitempty"`
	SignedTransactions [][]byte               `protobuf:"bytes,2,rep,name=signedTransactions,proto3" json:"signedTransactions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_velkarwalletd_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_velkarwalletd_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_velkarwalletd_proto_rawDescGZIP(), []int{21}
}

func (x *SendResponse) GetTxIDs() []string {
	if x != nil {
		return x.TxIDs
	}
	return nil
}

func (x *SendResponse) GetSignedTransactions() [][]byte {
	if x != nil {
		return x.SignedTransactions
	}
	return nil
}

// SendMany: NTMPool 扩展——单笔多输出批量打款（矿池打款铁律 C2：绝不逐地址串行发 tx→UTXO 互撞）。
// wallet-core 的 PaymentDestination::PaymentOutputs 原生支持多输出，一笔交易多个收款人（超 mass 上限时
// 底层生成器自动拆多笔，txIDs 返回全部）。
type SendManyOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToAddress     string                 `protobuf:"bytes,1,opt,name=toAddress,proto3" json:"toAddress,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendManyOutput) Reset() {
	*x = SendManyOutput{}
	mi := &file_velkarwalletd_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendManyOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendManyOutput) ProtoMessage() {}

func (x *SendManyOutput) ProtoReflect() protoreflect.Message {
	mi := &file_velkarwalletd_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendManyOutput.ProtoReflect.Descriptor instead.
func (*SendManyOutput) Descriptor() ([]byte, []int) {
	return file_velkarwalletd_proto_rawDescGZIP(), []int{22}
}

func (x *SendManyOutput) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *SendManyOutput) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type SendManyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outputs       []*SendManyOutput      `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	From          []string               `protobuf:"bytes,3,rep,name=from,proto3" json:"from,omitempty"`
	FeePolicy     *FeePolicy             `protobuf:"bytes,4,opt,name=feePolicy,proto3" json:"feePolicy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendManyRequest) Reset() {
	*x = SendManyRequest{}
	mi := &file_velkarwalletd_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendManyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendManyRequest) ProtoMessage() {}

func (x *SendManyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_velkarwalletd_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendManyRequest.ProtoReflect.Descriptor instead.
func (*SendManyRequest) Descriptor() ([]byte, []int) {
	return file_velkarwalletd_proto_rawDescGZIP(), []int{23}
}

func (x *SendManyRequest) GetOutputs() []*SendManyOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *SendManyRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SendManyRequest) GetFrom() []string {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *SendManyRequest) GetFeePolicy() *FeePolicy {
	if x != nil {
		return x.FeePolicy
	}
	return nil
}

type SendManyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxIDs         []string               `protobuf:"bytes,1,rep,name=txIDs,proto3" json:"txIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendManyResponse) Reset() {
	*x = SendManyResponse{}
	mi := &file_velkarwalletd_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendManyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendManyResponse) ProtoMessage() {}

func (x *SendManyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_velkarwalletd_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendManyResponse.ProtoReflect.Descriptor instead.
func (*SendManyResponse) Descriptor() ([]byte, []int) {
	return file_velkarwalletd_proto_rawDescGZIP(), []int{24}
}

func (x *SendManyResponse) GetTxIDs() []string {
	if x != nil {
		return x.TxIDs
	}
	return nil
}

type SignRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UnsignedTransactions [][]byte               `protobuf:"bytes,1,rep,name=unsignedTransactions,proto3" json:"unsignedTransactions,omitempty"`
	Password             string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	mi := &file_velkarwalletd_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_velkarwalletd_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_velkarwalletd_proto_rawDescGZIP(), []int{25}
}

func (x *SignRequest) GetUnsignedTransactions() [][]byte {
	if x != nil {
		return x.UnsignedTransactions
	}
	return nil
}

func (x *SignRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SignResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SignedTransactions [][]byte               `protobuf:"bytes,1,rep,name=signedTransactions,proto3" json:"signedTransactions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SignResponse) Reset() {
	*x = SignResponse{}
	mi := &file_velkarwalletd_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignResponse) ProtoMessage() {}

func (x *SignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_velkarwalletd_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignResponse.ProtoReflect.Descriptor instead.
func (*SignResponse) Descriptor() ([]byte, []int) {
	return file_velkarwalletd_proto_rawDescGZIP(), []int{26}
}

func (x *SignResponse) GetSignedTransactions() [][]byte {
	if x != nil {
		return x.SignedTransactions
	}
	return nil
}

type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_velkarwalletd_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_velkarwalletd_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_velkarwalletd_proto_rawDescGZIP(), []int{27}
}

type GetVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_velkarwalletd_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_velkarwalletd_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_velkarwalletd_proto_rawDescGZIP(), []int{28}
}

func (x *GetVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type BumpFeeRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Password                 string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	From                     []string               `protobuf:"bytes,2,rep,name=from,proto3" json:"from,omitempty"`
	UseExistingChangeAddress bool                   `protobuf:"varint,3,opt,name=useExistingChangeAddress,proto3" json:"useExistingChangeAddress,omitempty"`
	FeePolicy                *FeePolicy             `protobuf:"bytes,4,opt,name=feePolicy,proto3" json:"feePolicy,omitempty"`
	TxID                     string                 `protobuf:"bytes,5,opt,name=txID,proto3" json:"txID,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *BumpFeeRequest) Reset() {
	*x = BumpFeeRequest{}
	mi := &file_velkarwalletd_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BumpFeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BumpFeeRequest) ProtoMessage() {}

func (x *BumpFeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_velkarwalletd_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BumpFeeRequest.ProtoReflect.Descriptor instead.
func (*BumpFeeRequest) Descriptor() ([]byte, []int) {
	return file_velkarwalletd_proto_rawDescGZIP(), []int{29}
}

func (x *BumpFeeRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *BumpFeeRequest) GetFrom() []string {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *BumpFeeRequest) GetUseExistingChangeAddress() bool {
	if x != nil {
		return x.UseExistingChangeAddress
	}
	return false
}

func (x *BumpFeeRequest) GetFeePolicy() *FeePolicy {
	if x != nil {
		return x.FeePolicy
	}
	return nil
}

func (x *BumpFeeRequest) GetTxID() string {
	if x != nil {
		return x.TxID
	}
	return ""
}

type BumpFeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  [][]byte               `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	TxIDs         []string               `protobuf:"bytes,2,rep,name=txIDs,proto3" json:"txIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BumpFeeResponse) Reset() {
	*x = BumpFeeResponse{}
	mi := &file_velkarwalletd_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BumpFeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BumpFeeResponse) ProtoMessage() {}

func (x *BumpFeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_velkarwalletd_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BumpFeeResponse.ProtoReflect.Descriptor instead.
func (*BumpFeeResponse) Descriptor() ([]byte, []int) {
	return file_velkarwalletd_proto_rawDescGZIP(), []int{30}
}

func (x *BumpFeeResponse) GetTransactions() [][]byte {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *BumpFeeResponse) GetTxIDs() []string {
	if x != nil {
		return x.TxIDs
	}
	return nil
}

var File_velkarwalletd_proto protoreflect.FileDescriptor

const file_velkarwalletd_proto_rawDesc = "" +
	"\n" +
	"\x13velkarwalletd.proto\x12\rvelkarwalletd\"\x13\n" +
	"\x11GetBalanceRequest\"\x96\x01\n" +
	"\x12GetBalanceResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\x04R\tavailable\x12\x18\n" +
	"\apending\x18\x02 \x01(\x04R\apending\x12H\n" +
	"\x0faddressBalances\x18\x03 \x03(\v2\x1e.velkarwalletd.AddressBalancesR\x0faddressBalances\"c\n" +
	"\x0fAddressBalances\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\x04R\tavailable\x12\x18\n" +
	"\apending\x18\x03 \x01(\x04R\apending\"z\n" +
	"\tFeePolicy\x12 \n" +
	"\n" +
	"maxFeeRate\x18\x06 \x01(\x01H\x00R\n" +
	"maxFeeRate\x12$\n" +
	"\fexactFeeRate\x18\a \x01(\x01H\x00R\fexactFeeRate\x12\x18\n" +
	"\x06maxFee\x18\b \x01(\x04H\x00R\x06maxFeeB\v\n" +
	"\tfeePolicy\"\xfb\x01\n" +
	"!CreateUnsignedTransactionsRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\x12\x12\n" +
	"\x04from\x18\x03 \x03(\tR\x04from\x12:\n" +
	"\x18useExistingChangeAddress\x18\x04 \x01(\bR\x18useExistingChangeAddress\x12\x1c\n" +
	"\tisSendAll\x18\x05 \x01(\bR\tisSendAll\x126\n" +
	"\tfeePolicy\x18\x06 \x01(\v2\x18.velkarwalletd.FeePolicyR\tfeePolicy\"X\n" +
	"\"CreateUnsignedTransactionsResponse\x122\n" +
	"\x14unsignedTransactions\x18\x01 \x03(\fR\x14unsignedTransactions\"\x16\n" +
	"\x14ShowAddressesRequest\"1\n" +
	"\x15ShowAddressesResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x03(\tR\aaddress\"\x13\n" +
	"\x11NewAddressRequest\".\n" +
	"\x12NewAddressResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"R\n" +
	"\x10BroadcastRequest\x12\x1a\n" +
	"\bisDomain\x18\x01 \x01(\bR\bisDomain\x12\"\n" +
	"\ftransactions\x18\x02 \x03(\fR\ftransactions\")\n" +
	"\x11BroadcastResponse\x12\x14\n" +
	"\x05txIDs\x18\x01 \x03(\tR\x05txIDs\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse\"F\n" +
	"\bOutpoint\x12$\n" +
	"\rtransactionId\x18\x01 \x01(\tR\rtransactionId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\"\x9e\x01\n" +
	"\x15UtxosByAddressesEntry\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x123\n" +
	"\boutpoint\x18\x02 \x01(\v2\x17.velkarwalletd.OutpointR\boutpoint\x126\n" +
	"\tutxoEntry\x18\x03 \x01(\v2\x18.velkarwalletd.UtxoEntryR\tutxoEntry\"U\n" +
	"\x0fScriptPublicKey\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12(\n" +
	"\x0fscriptPublicKey\x18\x02 \x01(\tR\x0fscriptPublicKey\"\xb3\x01\n" +
	"\tUtxoEntry\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x04R\x06amount\x12H\n" +
	"\x0fscriptPublicKey\x18\x02 \x01(\v2\x1e.velkarwalletd.ScriptPublicKeyR\x0fscriptPublicKey\x12$\n" +
	"\rblockDaaScore\x18\x03 \x01(\x04R\rblockDaaScore\x12\x1e\n" +
	"\n" +
	"isCoinbase\x18\x04 \x01(\bR\n" +
	"isCoinbase\"<\n" +
	" GetExternalSpendableUTXOsRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"c\n" +
	"!GetExternalSpendableUTXOsResponse\x12>\n" +
	"\aEntries\x18\x01 \x03(\v2$.velkarwalletd.UtxosByAddressesEntryR\aEntries\"\x85\x02\n" +
	"\vSendRequest\x12\x1c\n" +
	"\ttoAddress\x18\x01 \x01(\tR\ttoAddress\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x12\n" +
	"\x04from\x18\x04 \x03(\tR\x04from\x12:\n" +
	"\x18useExistingChangeAddress\x18\x05 \x01(\bR\x18useExistingChangeAddress\x12\x1c\n" +
	"\tisSendAll\x18\x06 \x01(\bR\tisSendAll\x126\n" +
	"\tfeePolicy\x18\a \x01(\v2\x18.velkarwalletd.FeePolicyR\tfeePolicy\"T\n" +
	"\fSendResponse\x12\x14\n" +
	"\x05txIDs\x18\x01 \x03(\tR\x05txIDs\x12.\n" +
	"\x12signedTransactions\x18\x02 \x03(\fR\x12signedTransactions\"F\n" +
	"\x0eSendManyOutput\x12\x1c\n" +
	"\ttoAddress\x18\x01 \x01(\tR\ttoAddress\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\"\xb2\x01\n" +
	"\x0fSendManyRequest\x127\n" +
	"\aoutputs\x18\x01 \x03(\v2\x1d.velkarwalletd.SendManyOutputR\aoutputs\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04from\x18\x03 \x03(\tR\x04from\x126\n" +
	"\tfeePolicy\x18\x04 \x01(\v2\x18.velkarwalletd.FeePolicyR\tfeePolicy\"(\n" +
	"\x10SendManyResponse\x12\x14\n" +
	"\x05txIDs\x18\x01 \x03(\tR\x05txIDs\"]\n" +
	"\vSignRequest\x122\n" +
	"\x14unsignedTransactions\x18\x01 \x03(\fR\x14unsignedTransactions\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\">\n" +
	"\fSignResponse\x12.\n" +
	"\x12signedTransactions\x18\x01 \x03(\fR\x12signedTransactions\"\x13\n" +
	"\x11GetVersionRequest\".\n" +
	"\x12GetVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"\xc8\x01\n" +
	"\x0eBumpFeeRequest\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12\x12\n" +
	"\x04from\x18\x02 \x03(\tR\x04from\x12:\n" +
	"\x18useExistingChangeAddress\x18\x03 \x01(\bR\x18useExistingChangeAddress\x126\n" +
	"\tfeePolicy\x18\x04 \x01(\v2\x18.velkarwalletd.FeePolicyR\tfeePolicy\x12\x12\n" +
	"\x04txID\x18\x05 \x01(\tR\x04txID\"K\n" +
	"\x0fBumpFeeResponse\x12\"\n" +
	"\ftransactions\x18\x01 \x03(\fR\ftransactions\x12\x14\n" +
	"\x05txIDs\x18\x02 \x03(\tR\x05txIDs2\xb7\b\n" +
	"\rvelkarwalletd\x12S\n" +
	"\n" +
	"GetBalance\x12 .velkarwalletd.GetBalanceRequest\x1a!.velkarwalletd.GetBalanceResponse\"\x00\x12\x80\x01\n" +
	"\x19GetExternalSpendableUTXOs\x12/.velkarwalletd.GetExternalSpendableUTXOsRequest\x1a0.velkarwalletd.GetExternalSpendableUTXOsResponse\"\x00\x12\x83\x01\n" +
	"\x1aCreateUnsignedTransactions\x120.velkarwalletd.CreateUnsignedTransactionsRequest\x1a1.velkarwalletd.CreateUnsignedTransactionsResponse\"\x00\x12\\\n" +
	"\rShowAddresses\x12#.velkarwalletd.ShowAddressesRequest\x1a$.velkarwalletd.ShowAddressesResponse\"\x00\x12S\n" +
	"\n" +
	"NewAddress\x12 .velkarwalletd.NewAddressRequest\x1a!.velkarwalletd.NewAddressResponse\"\x00\x12M\n" +
	"\bShutdown\x12\x1e.velkarwalletd.ShutdownRequest\x1a\x1f.velkarwalletd.ShutdownResponse\"\x00\x12P\n" +
	"\tBroadcast\x12\x1f.velkarwalletd.BroadcastRequest\x1a .velkarwalletd.BroadcastResponse\"\x00\x12A\n" +
	"\x04Send\x12\x1a.velkarwalletd.SendRequest\x1a\x1b.velkarwalletd.SendResponse\"\x00\x12M\n" +
	"\bSendMany\x12\x1e.velkarwalletd.SendManyRequest\x1a\x1f.velkarwalletd.SendManyResponse\"\x00\x12A\n" +
	"\x04Sign\x12\x1a.velkarwalletd.SignRequest\x1a\x1b.velkarwalletd.SignResponse\"\x00\x12S\n" +
	"\n" +
	"GetVersion\x12 .velkarwalletd.GetVersionRequest\x1a!.velkarwalletd.GetVersionResponse\"\x00\x12J\n" +
	"\aBumpFee\x12\x1d.velkarwalletd.BumpFeeRequest\x1a\x1e.velkarwalletd.BumpFeeResponse\"\x00B8Z6github.com/velkarnet/velkar/cmd/velkarwallet/daemon/pbb\x06proto3"

var (
	file_velkarwalletd_proto_rawDescOnce sync.Once
	file_velkarwalletd_proto_rawDescData []byte
)

func file_velkarwalletd_proto_rawDescGZIP() []byte {
	file_velkarwalletd_proto_rawDescOnce.Do(func() {
		file_velkarwalletd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_velkarwalletd_proto_rawDesc), len(file_velkarwalletd_proto_rawDesc)))
	})
	return file_velkarwalletd_proto_rawDescData
}

var file_velkarwalletd_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_velkarwalletd_proto_goTypes = []any{
	(*GetBalanceRequest)(nil),                  // 0: velkarwalletd.GetBalanceRequest
	(*GetBalanceResponse)(nil),                 // 1: velkarwalletd.GetBalanceResponse
	(*AddressBalances)(nil),                    // 2: velkarwalletd.AddressBalances
	(*FeePolicy)(nil),                          // 3: velkarwalletd.FeePolicy
	(*CreateUnsignedTransactionsRequest)(nil),  // 4: velkarwalletd.CreateUnsignedTransactionsRequest
	(*CreateUnsignedTransactionsResponse)(nil), // 5: velkarwalletd.CreateUnsignedTransactionsResponse
	(*ShowAddressesRequest)(nil),               // 6: velkarwalletd.ShowAddressesRequest
	(*ShowAddressesResponse)(nil),              // 7: velkarwalletd.ShowAddressesResponse
	(*NewAddressRequest)(nil),                  // 8: velkarwalletd.NewAddressRequest
	(*NewAddressResponse)(nil),                 // 9: velkarwalletd.NewAddressResponse
	(*BroadcastRequest)(nil),                   // 10: velkarwalletd.BroadcastRequest
	(*BroadcastResponse)(nil),                  // 11: velkarwalletd.BroadcastResponse
	(*ShutdownRequest)(nil),                    // 12: velkarwalletd.ShutdownRequest
	(*ShutdownResponse)(nil),                   // 13: velkarwalletd.ShutdownResponse
	(*Outpoint)(nil),                           // 14: velkarwalletd.Outpoint
	(*UtxosByAddressesEntry)(nil),              // 15: velkarwalletd.UtxosByAddressesEntry
	(*ScriptPublicKey)(nil),                    // 16: velkarwalletd.ScriptPublicKey
	(*UtxoEntry)(nil),                          // 17: velkarwalletd.UtxoEntry
	(*GetExternalSpendableUTXOsRequest)(nil),   // 18: velkarwalletd.GetExternalSpendableUTXOsRequest
	(*GetExternalSpendableUTXOsResponse)(nil),  // 19: velkarwalletd.GetExternalSpendableUTXOsResponse
	(*SendRequest)(nil),                        // 20: velkarwalletd.SendRequest
	(*SendResponse)(nil),                       // 21: velkarwalletd.SendResponse
	(*SendManyOutput)(nil),                     // 22: velkarwalletd.SendManyOutput
	(*SendManyRequest)(nil),                    // 23: velkarwalletd.SendManyRequest
	(*SendManyResponse)(nil),                   // 24: velkarwalletd.SendManyResponse
	(*SignRequest)(nil),                        // 25: velkarwalletd.SignRequest
	(*SignResponse)(nil),                       // 26: velkarwalletd.SignResponse
	(*GetVersionRequest)(nil),                  // 27: velkarwalletd.GetVersionRequest
	(*GetVersionResponse)(nil),                 // 28: velkarwalletd.GetVersionResponse
	(*BumpFeeRequest)(nil),                     // 29: velkarwalletd.BumpFeeRequest
	(*BumpFeeResponse)(nil),                    // 30: velkarwalletd.BumpFeeResponse
}
var file_velkarwalletd_proto_depIdxs = []int32{
	2,  // 0: velkarwalletd.GetBalanceResponse.addressBalances:type_name -> velkarwalletd.AddressBalances
	3,  // 1: velkarwalletd.CreateUnsignedTransactionsRequest.feePolicy:type_name -> velkarwalletd.FeePolicy
	14, // 2: velkarwalletd.UtxosByAddressesEntry.outpoint:type_name -> velkarwalletd.Outpoint
	17, // 3: velkarwalletd.UtxosByAddressesEntry.utxoEntry:type_name -> velkarwalletd.UtxoEntry
	16, // 4: velkarwalletd.UtxoEntry.scriptPublicKey:type_name -> velkarwalletd.ScriptPublicKey
	15, // 5: velkarwalletd.GetExternalSpendableUTXOsResponse.Entries:type_name -> velkarwalletd.UtxosByAddressesEntry
	3,  // 6: velkarwalletd.SendRequest.feePolicy:type_name -> velkarwalletd.FeePolicy
	22, // 7: velkarwalletd.SendManyRequest.outputs:type_name -> velkarwalletd.SendManyOutput
	3,  // 8: velkarwalletd.SendManyRequest.feePolicy:type_name -> velkarwalletd.FeePolicy
	3,  // 9: velkarwalletd.BumpFeeRequest.feePolicy:type_name -> velkarwalletd.FeePolicy
	0,  // 10: velkarwalletd.velkarwalletd.GetBalance:input_type -> velkarwalletd.GetBalanceRequest
	18, // 11: velkarwalletd.velkarwalletd.GetExternalSpendableUTXOs:input_type -> velkarwalletd.GetExternalSpendableUTXOsRequest
	4,  // 12: velkarwalletd.velkarwalletd.CreateUnsignedTransactions:input_type -> velkarwalletd.CreateUnsignedTransactionsRequest
	6,  // 13: velkarwalletd.velkarwalletd.ShowAddresses:input_type -> velkarwalletd.ShowAddressesRequest
	8,  // 14: velkarwalletd.velkarwalletd.NewAddress:input_type -> velkarwalletd.NewAddressRequest
	12, // 15: velkarwalletd.velkarwalletd.Shutdown:input_type -> velkarwalletd.ShutdownRequest
	10, // 16: velkarwalletd.velkarwalletd.Broadcast:input_type -> velkarwalletd.BroadcastRequest
	20, // 17: velkarwalletd.velkarwalletd.Send:input_type -> velkarwalletd.SendRequest
	23, // 18: velkarwalletd.velkarwalletd.SendMany:input_type -> velkarwalletd.SendManyRequest
	25, // 19: velkarwalletd.velkarwalletd.Sign:input_type -> velkarwalletd.SignRequest
	27, // 20: velkarwalletd.velkarwalletd.GetVersion:input_type -> velkarwalletd.GetVersionRequest
	29, // 21: velkarwalletd.velkarwalletd.BumpFee:input_type -> velkarwalletd.BumpFeeRequest
	1,  // 22: velkarwalletd.velkarwalletd.GetBalance:output_type -> velkarwalletd.GetBalanceResponse
	19, // 23: velkarwalletd.velkarwalletd.GetExternalSpendableUTXOs:output_type -> velkarwalletd.GetExternalSpendableUTXOsResponse
	5,  // 24: velkarwalletd.velkarwalletd.CreateUnsignedTransactions:output_type -> velkarwalletd.CreateUnsignedTransactionsResponse
	7,  // 25: velkarwalletd.velkarwalletd.ShowAddresses:output_type -> velkarwalletd.ShowAddressesResponse
	9,  // 26: velkarwalletd.velkarwalletd.NewAddress:output_type -> velkarwalletd.NewAddressResponse
	13, // 27: velkarwalletd.velkarwalletd.Shutdown:output_type -> velkarwalletd.ShutdownResponse
	11, // 28: velkarwalletd.velkarwalletd.Broadcast:output_type -> velkarwalletd.BroadcastResponse
	21, // 29: velkarwalletd.velkarwalletd.Send:output_type -> velkarwalletd.SendResponse
	24, // 30: velkarwalletd.velkarwalletd.SendMany:output_type -> velkarwalletd.SendManyResponse
	26, // 31: velkarwalletd.velkarwalletd.Sign:output_type -> velkarwalletd.SignResponse
	28, // 32: velkarwalletd.velkarwalletd.GetVersion:output_type -> velkarwalletd.GetVersionResponse
	30, // 33: velkarwalletd.velkarwalletd.BumpFee:output_type -> velkarwalletd.BumpFeeResponse
	22, // [22:34] is the sub-list for method output_type
	10, // [10:22] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_velkarwalletd_proto_init() }
func file_velkarwalletd_proto_init() {
	if File_velkarwalletd_proto != nil {
		return
	}
	file_velkarwalletd_proto_msgTypes[3].OneofWrappers = []any{
		(*FeePolicy_MaxFeeRate)(nil),
		(*FeePolicy_ExactFeeRate)(nil),
		(*FeePolicy_MaxFee)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_velkarwalletd_proto_rawDesc), len(file_velkarwalletd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_velkarwalletd_proto_goTypes,
		DependencyIndexes: file_velkarwalletd_proto_depIdxs,
		MessageInfos:      file_velkarwalletd_proto_msgTypes,
	}.Build()
	File_velkarwalletd_proto = out.File
	file_velkarwalletd_proto_goTypes = nil
	file_velkarwalletd_proto_depIdxs = nil
}
