import { spawn } from 'node:child_process';
import { writeFileSync } from 'node:fs';
const CHROME = 'C:/Program Files/Google/Chrome/Application/chrome.exe';
const [ORIGIN, LANG, W, OUT] = [process.argv[2], process.argv[3], Number(process.argv[4]), process.argv[5]];
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const chrome = spawn(CHROME, ['--headless=new','--disable-gpu','--no-sandbox',`--window-size=${W},900`,'--remote-debugging-port=9228','about:blank'], { stdio: 'ignore' });
await sleep(2500);
const page = (await (await fetch('http://127.0.0.1:9228/json')).json()).find((x) => x.type === 'page');
const ws = new WebSocket(page.webSocketDebuggerUrl);
let id = 0; const pending = new Map();
const send = (m, p = {}) => new Promise((res) => { const n = ++id; pending.set(n, res); ws.send(JSON.stringify({ id: n, method: m, params: p })); });
ws.onmessage = (e) => { const m = JSON.parse(e.data); if (m.id && pending.has(m.id)) { pending.get(m.id)(m.result); pending.delete(m.id); } };
await new Promise((r) => { ws.onopen = r; });
const ev = async (x) => (await send('Runtime.evaluate', { expression: x, returnByValue: true, awaitPromise: true })).result?.value;
await send('Page.enable');
await send('Emulation.setDeviceMetricsOverride', { width: W, height: 900, deviceScaleFactor: 2, mobile: false });
await send('Page.navigate', { url: `${ORIGIN}/` });
await sleep(3000);
await ev(`localStorage.setItem("ntm_lang","${LANG}"); true`);
await send('Page.navigate', { url: `${ORIGIN}/` });
await sleep(5000);
const r = await send('Page.captureScreenshot', { format: 'png', clip: { x: 0, y: 0, width: W, height: 130, scale: 2 } });
writeFileSync(OUT, Buffer.from(r.data, 'base64'));
console.log('saved', OUT);
ws.close(); chrome.kill(); process.exit(0);
